# The west manifest file (west.yml) for the hpmicro SDK.
#
# The per-workspace west configuration file, .west/config,
# specifies the location of this manifest file like this:
#
#     [manifest]
#     path = sdk_glue

########################################
##  zephyr                    v3.7.0  ##
##  hpm_sdk                   v1.6.0  ##
########################################
manifest:
  version: "1.0"

  remotes:
    - name: oss
      url-base: git@192.168.11.211:oss
    - name: sw
      url-base: git@192.168.11.211:sw
    - name: github
      url-base: https://github.com/hpmicro

  defaults:
    remote: oss

  projects:
    - name: zephyr
      repo-path: hpm_zephyrproject
      revision: v3.7.0_hpm_master
      import:
        name-allowlist:
          - west-commands
    - name: sdk_env
      remote: github
      repo-path: sdk_env
      path: sdk_env
      revision: v1.6.0
      submodules: true
    - name: canopennode
      remote: github
      repo-path: canopennode
      path: modules/lib/canopennode
      revision: dec12fa3f0d790cafa8414a4c2930ea71ab72ffd

  # West-related configuration for the sdk_glue repository.
  self:
    path: sdk_glue
    west-commands: scripts/west-commands.yml
