# The west manifest file (west.yml) for the hpmicro SDK.
#
# The per-workspace west configuration file, .west/config,
# specifies the location of this manifest file like this:
#
#     [manifest]
#     path = sdk_glue

########################################
##  zephyr                    v3.4.0  ##
##  hpm_sdk                   v1.5.0  ##
########################################
manifest:
  version: "1.0"

  remotes:
    - name: oss
      url-base: git@192.168.11.211:oss
    - name: sw
      url-base: git@192.168.11.211:sw

  defaults:
    remote: oss

  projects:
    - name: zephyr
      repo-path: hpm_zephyrproject
      revision: v3.7.0-hpm-branch
      import:
        name-allowlist:
          - west-commands
    - name: sdk_env
      path: sdk_env
      url: https://github.com/hpmicro/sdk_env.git
      revision: v1.6.0
      submodules: true

  # West-related configuration for the sdk_glue repository.
  self:
    path: sdk_glue
