# The west manifest file (west.yml) for the hpmicro SDK.
#
# The per-workspace west configuration file, .west/config,
# specifies the location of this manifest file like this:
#
#     [manifest]
#     path = sdk_glue

########################################
##  zephyr                    v3.7.0  ##
##  hpm_sdk                   v1.6.0  ##
########################################
manifest:
  version: "1.0"

  remotes:
    - name: test
      url-base: git@192.168.11.211:oss
    - name: github
      url-base: https://github.com/hpmicro
    - name: cherry-embedded
      url-base: https://github.com/cherry-embedded/

  defaults:
    remote: github

  projects:
    - name: zephyr
      remote: test
      # repo-path: zephyr
      # revision: v3.7.0_hpm_sdk_v1.6.0
      repo-path: hpm_zephyrproject
      revision: v3.7.0_hpm_master
      import:
        name-allowlist:
          - west-commands
          - fatfs
    - name: sdk_env
      repo-path: sdk_env
      path: sdk_env
      revision: v1.6.0
      submodules: true
    - name: canopennode
      repo-path: canopennode
      path: modules/lib/canopennode
      revision: dec12fa3f0d790cafa8414a4c2930ea71ab72ffd
    - name: lvgl
      repo-path: zephyr_lvgl
      path: modules/lib/gui/lvgl
      revision: 2b498e6f36d6b82ae1da12c8b7742e318624ecf5
    - name: CherryUSB
      remote: cherry-embedded
      repo-path: CherryUSB
      path: modules/lib/CherryUSB
      revision: 537ccfd945382491b97b75ca380949b8cbff39cd

  # West-related configuration for the sdk_glue repository.
  self:
    path: sdk_glue
    west-commands: scripts/west-commands.yml
